name: fiscal
description: Application for personal finance and budget management

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #tdd
  equatable: ^2.0.0
  get_it: ^7.1.3
  dartz: ^0.10.0-nullsafety.2
  rxdart: ^0.27.0

  #state management
  provider: ^5.0.0

  #backend
  sqflite: ^2.0.0+3

  #ui
  syncfusion_flutter_charts: ^19.1.59

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Signika
      fonts:
        - asset: assets/fonts/signika/Signika-Regular.ttf
          weight: 400
        - asset: assets/fonts/signika/Signika-Medium.ttf
          weight: 500
        - asset: assets/fonts/signika/Signika-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/signika/Signika-Bold.ttf
          weight: 700
        - asset: assets/fonts/signika/Signika-Light.ttf
          weight: 300
    - family: Patua One
      fonts:
        - asset: assets/fonts/patua/PatuaOne-Regular.ttf
          weight: 300